# Generated by Django 4.2.6 on 2023-10-06 12:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IceCream',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('compound', models.CharField(max_length=150)),
                ('calories', models.CharField(max_length=25)),
                ('proteins', models.CharField(max_length=25)),
                ('carbonhydrates', models.CharField(max_length=25)),
                ('fats', models.CharField(max_length=25)),
                ('rating', models.IntegerField(default=0)),
            ],
        ),
    ]
