# Generated by Django 4.2.6 on 2023-10-07 17:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('icedreamapp', '0002_icecream_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='icecream',
            name='image',
            field=cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image'),
        ),
    ]
