# Generated by Django 4.2.6 on 2023-10-10 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icedreamapp', '0005_cart_total'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='total',
        ),
        migrations.AddField(
            model_name='cartitem',
            name='total',
            field=models.IntegerField(default=0),
        ),
    ]
