# Generated by Django 4.2.6 on 2023-10-10 17:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icedreamapp', '0006_remove_cart_total_cartitem_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='total',
            field=models.FloatField(default=0),
        ),
    ]
