# Generated by Django 4.2.6 on 2023-10-13 13:25

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('icedreamapp', '0008_icecream_special'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConeBox',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('price', models.FloatField(default=0)),
                ('size', models.CharField(max_length=50, unique=True)),
                ('image', cloudinary.models.CloudinaryField(default='image', max_length=255, verbose_name='image')),
            ],
        ),
        migrations.AddField(
            model_name='icecream',
            name='type',
            field=models.CharField(choices=[('Ice Cream', 'Ice Cream'), ('Sorbet', 'Sorbet'), ('Vegan', 'Vegan')], default='IceCream', max_length=32),
        ),
    ]
